version: "3.1"

services:
  hdpmst:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    volumes:
      - .:/root/staging
      - name0:/hadoop/hdfs/namenode
    networks:
      - mynet
    environment:
      - HADOOP_MULTINODE=yes
  hdp1:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    volumes:
      - data1:/hadoop/hdfs/datanode
    networks:
      - mynet
    environment:
      - HADOOP_MASTER=hdpmst
  hdp2:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
    volumes:
      - data2:/hadoop/hdfs/datanode
    networks:
      - mynet
    environment:
      - HADOOP_MASTER=hdpmst

  spk_cli:
    image: mkenjis/ubspkcli_yarn_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    ports:
      - 4040:4040
      - 18080:18080

networks:
  mynet:
    external:
       name: mynet

volumes:
  name0:
  data1:
  data2:
